language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - osx


before_script:
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustfmt --version
  - env

script:
  - cargo build --verbose
  - sudo cargo test --verbose -- --test-threads=1
  - ./format.sh --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
