language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - osx

before_script:
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustfmt --version
  - env

script:
  - cargo build --verbose
  - cargo test --verbose
  - ./format.sh --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
