language: rust
cache: cargo
rust:
  - nightly
  - stable
  - beta
  - 1.38.0
os:
  - osx


before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - env

script:
  - cargo build --verbose
  - sudo cargo test --verbose -- --test-threads=1
  - sudo chmod -R o+w target/
  # Format only on nightly, since that is where rustfmt-nightly compiles
  - if [ "${TRAVIS_RUST_VERSION}" = "stable" ]; then
      rustup component add rustfmt;
      rustfmt --version;
      cargo fmt -- --check;
    else
      echo "Not checking formatting on this build";
    fi

notifications:
  email:
    on_success: never
    on_failure: never
