[package]
name = "pfctl"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <faern@faern.net>", "Andrej Mihajlov <and@mullvad.net>"]
license = "MIT/Apache-2.0"
description = "Library for interfacing with the Packet Filter (PF) firewall on macOS"
readme = "README.md"
keywords = ["pf", "pfctl", "firewall", "macos", "network"]
categories = ["network-programming", "os", "os::unix-apis", "api-bindings", "command-line-utilities"]
build = "build.rs"

[badges]
travis-ci = { repository = "mullvad/pfctl-rs" }


[dependencies]
errno = "0.2"
error-chain = "0.11"
ioctl-sys = "0.5.2"
libc = "0.2.29"
derive_builder = "0.5"
ipnetwork = "0.12"

[dev-dependencies]
lazy_static = "0.2"
pfctl_test = { path = "tests/pfctl_test" }
assert_matches = "1.1.0"
uuid = { version = "0.5", features = ["v4"] }

[build-dependencies]
bindgen = "0.31"
